import { authFeature } from './reducer';

// All per-property selectors are auto-generated by `createFeature`. We re-export
// them here under the library's existing public names so consumers are unaffected.

export const {
    selectAuthState,
    selectIsAuthenticated,
    selectUser,
    selectIsPasswordBeingChanged,
    selectUsersList, // list of colleagues of the current user for example
    selectIsSignUpLoading,
    selectIsSendActivationCodeLoading,
    selectIsUserCreated,
    selectIsLoginLoading
} = authFeature;

/** Public alias — state field is `error`, generated selector is `selectError`. */
export const selectLogInError = authFeature.selectError;

/** Public alias — state field is `isUserActivated`, generated selector is `selectIsUserActivated`. */
export const selectIsActivated = authFeature.selectIsUserActivated;
